# Assignments

Course assignments include (in increasing order of importance):

- minute papers (and class participation)
- labs
- quizzes, and
- projects

The Assignments page linked on the [main course website](https://thomaselove.github.io/431-2025/) provides links to additional information on these assignments.

## Deadlines for Assignments

All deadlines are posted as part of the [Course Calendar](https://thomaselove.github.io/431-2025/calendar.html), and the Calendar is the final word for all deadlines.

- On every assignment, Lab, Quiz, project-related task, whatever, we will be delighted to respond to questions **up to 12 hours before** the assignment is due. After that time, you may wind up on your own. The reason for this is that Professor Love and the teaching assistants will regularly post responses to frequently asked questions about assignments, and we need sufficient time to accomplish this task.

## Using Artificial Intelligence Tools

See @sec-ai for details on this course's policies on using AI composition software (such as ChatGPT) for assignments in this course.

## Minute Papers

During the semester, there are several Minute Papers scheduled. In this class, a Minute Paper is a short survey (completed using a Google Form) where you will answer a few questions about how the course is going for you. To complete the Minute Paper, you'll need to log into Google with your CWRU account. The [Welcome to 431 Survey](https://bit.ly/431-2025-welcome) uses a similar format, but is more extensive than a typical Minute Paper. 

Each Minute Paper ideally takes less than five minutes to complete, and is best done right at the end of Tuesday's class. The Minute Papers are actually due at noon Wednesday to give you some time to reflect, if you'd like, or if you're in a hurry at the end of Tuesday's class. The Minute Papers are linked on the [431 Minute Paper page](https://github.com/THOMASELOVE/431-minute-2025).

You **should** complete the Minute Paper even if you weren't able to attend the most recent class.

Only Professor Love sees the results of the Minute Papers with identifying information. He then summarizes findings without identifying people and addresses those as part of the README discussion in the Thursday class whenever possible.

Professor Love reserves the right to change the number of minute papers depending on how the class is going during the semester. 

## Class Participation

We cannot emphasize enough how much we want to hear from you about things that are relevant to this course. 

1. If you're not shy, ask questions during class. Come to the (virtual) TA office hours if you need help.
2. Contribute to Campuswire with questions, answers and helpful comments. That'll help us recognize you as someone trying to improve their understanding.
  - If you find **typos** in the materials (code, slides, the Notes, this syllabus) send them to us on Campuswire. 
  - See a cool visualization online? A nice use of statistical methods or design in a paper? Share them with us on Campuswire.
3.  Email Professor Love if you want to discuss something that doesn't fit on Campuswire or in a conversation with a TA. Visit with him before or after class. Make an appointment to talk with him if you have something to discuss that doesn't work well in email. 
  - It's always helpful if Professor Love knows who you are, and this is an especially difficult thing to achieve with a large class and masks.

## Labs

During the semester, there are **seven** main lab assignments (called Labs 1-6 and Lab X) scheduled. Professor Love reserves the right to adjust the number of labs depending on how the class is going during the semester. 

The [Course Calendar](https://thomaselove.github.io/431-2025/calendar.html) provides deadlines for all Labs, and the [431-Labs page](https://github.com/THOMASELOVE/431-labs-2025) links to additional information on all Labs.

- Most labs require straightforward demonstrations of mastery for core principles and fundamental skills. Some require deeper dives into more technically sophisticated material. 
- Most labs ask you to clean/visualize/analyze some data that we provide to you, and also to react to something we're reading at the same time in the Spiegelhalter book. 
- You should anticipate that some coding in R **and** writing at least one essay will be required in most labs.

Lab assignments are submitted through [Canvas](https://canvas.case.edu). The link to post your responses for each Lab will appear in time for you to submit the work, usually just after the deadline for the preceding Lab has passed. 

Each lab is associated with a deadline. Late work is permitted, but penalized (see the [431-Labs page](https://github.com/THOMASELOVE/431-labs-2025) for more details.)

### A few tips for Early Lab Work

1. When writing anything for this course in English, use complete sentences, not just bullet points.
2. Clearly mark each Question in each Lab. There is no need to repeat the question before answering it, although you are welcome to do so.
3. You are welcome to discuss each Lab with anyone, including Professor Love, the teaching assistants, or your colleagues, but your answer must be prepared by you alone. We especially encourage you to take advantage of TA office hours and Campuswire.
4. Don't leave anything until the last day. Allow time for computer problems.

## Quizzes

During the semester, you will have two quizzes to complete. Each quiz is taken online via a Google Form (like the Minute Papers or the [Welcome to 431 survey](https://bit.ly/431-2025-welcome-survey).) Each quiz includes both short-answer and multiple-choice items. The quizzes focus on whether you can apply the tools developed in class to address small problems.

The [Course Calendar](https://thomaselove.github.io/431-2025/calendar.html) provides deadlines for each of the Quizzes, and the [431-Quiz page](https://github.com/THOMASELOVE/431-quizzes-2025) provides links to instructions for Quizzes.

You will receive access to the quiz on the Thursday before it is due (the next Wednesday at noon), and each quiz is designed to take 4-8 hours to complete, so the time pressure should be minimal. **If you need to make alternate arrangements for a Quiz, please contact Professor Love via email as soon as possible**, at least a week before a Quiz is released. 

### About the Quizzes

1. Quizzes typically involve 20-30 questions. 
2. The questions are not arranged in any particular order, and you should answer all questions.
3. All questions involve relatively short responses, sometimes after working through a detailed analysis.
4. You will have the opportunity to edit your responses after completing the Quiz, but this must be completed by the deadline.
5. You are welcome (even encouraged) to consult the materials provided on the course website, but you are **not** allowed to discuss the questions on the Quizzes with anyone other than Professor Love or the teaching assistants.
6. The use of large language models (like ChatGPT) and other AI support not provided in RStudio is not permitted on the Quizzes.
7. We do not guarantee to answer questions we receive about the Quiz less than 3 hours prior to the Quiz submission deadline. As noted above, we will **not** use Campuswire for Quiz questions, but instead an alternate approach we will provide to you with each quiz.
8. Quizzes that are more than an hour late will **not** be accepted, except in truly remarkable circumstances.
9. An answer sketch for each Quiz will be made available within 48 hours of the deadline. 
10. Grades for the Quizzes are usually available within 48 hours of the deadline. 
11. If you feel Professor Love has made an error in grading your Quiz, please let him know directly, by email, as soon as possible.

## Projects

During the semester, you will have two projects to complete. 

- [Project A](https://thomaselove.github.io/431-projectA-2025/) anticipates you using materials from the first 10 classes, working with data Dr. Love provides to you.
- Project B anticipates you using materials from the entire term, working with either NHANES data, or a data set you identify yourself.

The [Course Calendar](https://thomaselove.github.io/431-2025/calendar.html) provides deadlines for all Project elements, and each project will have a special website of its own which will provide full directions. 

## Why Two Projects? 

The main reason is that I can't figure out a way to get you to think about all of the things I hope you'll learn from this course in a single Project. Another important reason is that I want you to be able to make mistakes during the semester without worrying about it too much, and having two projects spreads out this learning a bit.

1. I set different tasks for Project A and for Project B, allowing us to touch on a wider fraction of the things I hope you'll learn in 431. 
2. I give much more guidance and written feedback in Project A than in Project B.
3. We have to evaluate each of your projects quickly, and there are many students in the class. Knowing the data set you'll be working with helps us manage this.
4. Having a broad range of activities to evaluate helps reduce the cost of a mistake on any one of them, so that we can build on what you do well.
5. All of Project A can be done using materials discussed in Classes 1-15.
