# Grading

Over the past five years, essentially all students taking the course have eventually earned either an "A", a "B" or an "Incomplete" in 431. I don't see a reason why this won't also be the case this year. The course cannot be taken "pass/fail."

## Grading Breakdown

Grading standards apply in the same way for all students, regardless of whether they are enrolled in PQHS 431, CRSP 431 or MPHP 431. Students in this class are not in competition with each other for grades. I have no set percentage of students who will receive any particular grade. We aim for substantial and timely feedback from the teaching assistants and myself on all elements of the course.

The course grade is based on four key areas of demonstrated accomplishment. 

Course grades are based primarily on performance on labs, projects and quizzes. Your course grade will be calculated as follows:

- 6 main labs (Labs 1-6, at 50 points each) but we count the top 5, for a possible score of 250 points.
- 9 minute papers (at 5 points each) for a possible score of 45 points.
    - If any lab or minute paper is more than 59 minutes late, you will lose points if it’s in by Thursday at noon (24 hours late.) After Thursday at noon, we will not accept your work. 
- Welcome to 431 Survey (10 points) and Lab 7 (25 points) for a possible total of 35 points.
- Class Participation scored by Professor Love out of a possible 25 points.
- Project A is worth 120 points (20 for the plan, 100 for the portfolio).
- Project B is worth 150 points.
- Two quizzes each initially scored out of 100 points, with each score multiplied by 1.15 to get a result out of 115 points. Then, I will multiply the better grade by 1.2 and the worse one by 0.8, to reach a total of 230 possible points.

That is a total of 855 possible points, but we will pretend it is out of 850.

- In addition, there will be several bonus opportunities through the semester (including, for example, one buried in this Syllabus). Those opportunities will add up to fewer than 25 points.

The minimum necessary score to receive a B grade in the class is 600 points (that's 70.6% of 850.)

The minimum necessary score to receive an A grade in the class is 725 points (that's 85.3% of 850.)

We follow the University's Incomplete Policy, as described below.

## Grading Class Participation

Student Class Participation grades are determined by Professor Love out of a maximum of 25 points. This determination is based on actions that help the class, as awarded during the semester

These points have a small impact, generally, but include things like:

- finding typographical or coding errors in Professor Love's slides, notes and other published materials. Professor Love makes occasional typographic and grammatical errors, which irritate him enormously. Please post to Campuswire the details of any typos or errors you find in this syllabus or any other course materials. If you are the first to let us know, and we make the change, you will receive some credit in your class participation grade.
- asking especially helpful questions in the Minute Papers or on Campuswire or in person
- providing helpful responses to questions and engaging in the discussion on Campuswire
- identifying interesting visualizations or uses of ideas we're discussing in class in the popular or scientific media (this is also done via Campuswire.)
- plus a few other things that come under the general heading of "being helpful."

I also connect with the TAs on this sort of issue, and take into account whether or not you've been completing work in a timely fashion, and either attending TA office hours or asking/answering questions on Campuswire or both.

## Grading Labs

The six Main Labs are graded by the Teaching Assistants, according to a rubric and answer sketch. In grading labs, everything counts, including the quality of the presentation, as well as the coding and statistical work. 

For each of Labs 1-6, we publish a detailed answer sketch 48 hours after the Lab's submission deadline. Later, when the grades become available (roughly one week after the deadline) you will also receive the grading rubric used by the teaching assistants. Along with the grade, on-time labs will receive modest feedback about the work. 

All Labs should be turned in by the deadline specified on the [Course Calendar](https://thomaselove.github.io/431-2025/calendar.html). In this class, it is far better to turn in timely, but only partially complete work than nothing at all. We don't give extensions on Labs. Instead, we use the following grading policy.

- Note that your lowest lab score (out of Labs 1-6) over the course of the semester will be dropped before we calculate your lab grade.
- To receive full credit on a Lab, it must be received on Canvas no later than 59 minutes after the posted deadline. (This allows for small issues with uploading to Canvas to occur without penalty.)
- Labs that are turned in 1-48 hours after the deadline will lose 10 points for late work.
- No extensions to Lab deadlines will be made this semester. Labs turned in more than 48 hours after the deadline will receive no credit, since by then the Lab Sketch will be posted.

Your lowest lab score (out of Labs 1-6) over the course of the semester will be dropped before we calculate your overall lab grade. 

- If you decide to skip a lab, please submit a note to Canvas by the deadline saying that you are skipping the lab. You cannot skip Lab X.
- Should you run the risk of needing to miss more than one lab during the semester, contact Professor Love via email before doing so.

## Lab Appeal Policy - Request a Review via Google Form

Clarification of concerns related to potential typographical or other errors in our Lab answer sketches is welcome at any time, but haggling over points on assignments can be a real time sink in a large class. To that end, students are **requested not to dispute** any grading on Labs during the semester, but instead to request a review using the [Lab Regrade Request Form](https://github.com/THOMASELOVE/431-labs-2025/tree/main?tab=readme-ov-file#lab-regrade-requests-will-be-reviewed-in-december).

Should you receive a lower grade on a Lab than you feel you deserve based on the feedback the TA provides, the answer sketch and the grading rubric, you can submit a request for a regrade by Professor Love as follows...

We use this form to handle almost all grading errors and regrade requests on Labs. The only exception to this policy is when you believe we've made an arithmetic error in summing up your points on a lab. If that happens, just email Dr. Love to get it straightened out. The Form is used for all other regrade situations.

- If you want Dr. Love to review your grade on one (or more) of Labs 1-6, fill out the Lab Regrade Request Form anytime before the deadline on the Course Calendar.
- When all other course work has been graded, Dr. Love will open the form. If you have requested additional points that could change your course grade, he'll review your request. If not, then he won't.
- Disputing a grade on a homework with a teaching assistant is pointless. 
- Professor Love is responsible for all final grading decisions, and if you have a concern, you should submit your request through the form.
    
Students are welcome to ask questions of Professor Love about grading during the term. The TAs and Professor Love are happy to discuss in a general sense any questions about an assignment, but no grades will be changed until the end of the term. 
    - The one exception is if there is a mistake in adding up points, or some similar clerical error. If you find such an issue, please bring it to Professor Love's attention via email, and such problems will be corrected immediately.

The main advantage of this system is that it saves all of us the hassle of haggling over points that are never going to mean anything anyway. It also provides "equal access" to students who are too timid to express their concerns. Finally, if there is an issue with grading a particular problem or assignment that needs to be reconsidered, Professor Love will have access to all papers and can make a universal decision^[I got this idea from Jessica Utts.].

## Grading the Quizzes

Each quiz will be graded solely by Professor Love. A detailed answer sketch and grading rubric will be provided to you when grades are available, within 48 hours of the quiz deadline. 

As noted above, Professor Love weights your stronger Quiz performance at 60% and your other Quiz at 40% in compiling your course grade.

## Grading the Projects

Some elements of each project will be graded by Professor Love, and others by the teaching assistants.

Students who cannot complete a project (either A or B) in a timely fashion will receive an incomplete grade until both Projects are completed. A stiff penalty will be applied to late work on projects. 

Once the complete project instructions are available, please contact Professor Love directly if you are in any way concerned about your ability to complete a project on time.

## Late Assignments

If an emergency arises that will keep you from timely completion of work that has a deadline, like a lab, minute paper, or the like, send an email directly to Professor Love saying the following:

I have an emergency that will keep me from completing (list things you’re worried about completing) in a timely fashion. I will contact you again when I am able to make plans.

Professor Love will respond with “OK” and temporarily excuse you from things until you send a “re-connection” email to make plans for making up the work you missed, at which time he’ll evaluate the situation and together you can make that plan. At no time do you owe us any information about your health or the nature of the emergency.

## Incomplete Grades

Here is the official University policy:

> The grade of Incomplete is assigned at the discretion of an instructor provided that:

> 1.	There are extenuating circumstances, explained to the instructor before the assignment of the grade, which clearly justify an extension of time beyond the requirements established for other students in the class. It is the student's responsibility to notify the instructor of the circumstances preventing completion.

> 2.	The student has been passing the course and only a small segment of the course remains to be completed, such as a term paper, for which the extenuating circumstances justify a special exception.

> An Incomplete grade may not be assigned if a student is absent from a final examination, unless the dean has authorized the absence. Unauthorized absence from a final examination will result in a failing grade. When the student completes the work, the Incomplete is changed to an A, B, C, D, P, F, or NP.

> All work for the incomplete grade must be made up and the change of grade recorded in the Office of the University Registrar by the date specified by the instructor, but no later than the last day of class in the semester following the one in which the Incomplete was received. A student who has a permanent Incomplete for a required course must retake the course in a later term. If the student cannot complete the work by the end of the following semester, he or she must petition for an extension which must be endorsed by the instructor, explain the reasons why the work has not been completed, and include a new date for completion. Students will be allowed only one extension of no more than one additional semester to complete the work for an Incomplete grade.
