# General Policies

All Case Western Reserve University policies apply to this class, including those summarized below. To the extent that those policies are unclear, I would regard an appropriate code of conduct as mirroring  [this one from the R Consortium](https://github.com/RConsortium/RCDI-WG/blob/master/conduct/code-of-conduct.md).

Any concerns or questions regarding these general policies, the teaching assistants or the course itself should be directed to Professor Love, if at all possible.

## Attendance

Things happen, and people occasionally cannot make it to class in person. For 431, we expect all students to attend at least 22 of the 25 sessions in person.

- If you need to miss a class session, or even two, just review the materials and move on, and please feel encouraged to ask for help.
- If you must miss **more than two classes** in a row, then it is your responsibility to email Professor Love as soon as possible to let him know. 
  - An appropriate email would read "I am unable to attend class on [specific dates] and I will complete all necessary work while I am away." No additional explanation is required.

## Auditing 

Enrolled students and teaching assistants are the only people permitted to attend the course, without special permission from Professor Love. 

- I do not permit anyone to audit the course who has not previously taken it, without exception. 

## Recordings 

We aim to have video recordings available on [Canvas](https://canvas.case.edu/) after several class sessions.

- "Live" Zoom attendance can be a problem, in that remote students will not be able to interact with the class.
- Technical problems may occur during the semester with the recordings.
- You should assume that anything you say in class will be recorded.

## University Required Language

### University Enrichment & Engagement

> It is the intent that all students regardless of their background and perspective be well-served by this class.  Further, we intend to present material whose content is respectful and deliver it in a respectful manner.  We expect that all students, instructors and guests will help foster an atmosphere of respect, trust and safety in the classroom. 
 
> If you have suggestions for how to make the class content or environment more respectful, or have specific incidents to report, please reach out to the instructor.  If you are not comfortable reaching out to the instructor, feel free to reach out to someone else, such as the School of Medicine Graduate Education Office (`som-geo@case.edu`) or the [Office of Campus Enrichment and Engagement](https://case.edu/enrichment-engagement/). More information on University policy and resources is available [on their website](https://case.edu/enrichment-engagement/).
 
### Disability Accommodations

> In accordance with federal law, if you have a documented disability, you may be eligible to request accommodations from Disability Resources. In order to be considered for accommodations you must first register with the Disability Resources office. Please contact their office to register at 216.368.5230 or [follow this link to get more information on how to begin the process](https://case.edu/studentlife/disability/getting-started). Please keep in mind that accommodations are not retroactive.
 
### Academic Integrity 

> [Click here to obtain the PDF file describing Academic Integrity for Graduate Courses](https://case.edu/gradstudies/sites/default/files/2018-04/SGS-Academic-Integrity-Policies-and-Rules.pdf)

### AI (Artificial Intelligence)

> Students at Case Western Reserve University are expected to uphold the highest ethical standards of academic conduct. Academic integrity addresses all forms of academic dishonesty, including cheating, plagiarism, misrepresentation, obstruction, and submitting without permission work to one course that was completed for another course. Please review the complete academic integrity policy for additional information, including an overview of the processes & procedures for reporting academic misconduct.

> In addition, we recommend that faculty clearly describe their course-specific expectations for students’ use of AI tools.

Note that I have done this on an assignment-level basis.

> Students are encouraged to consult with the instructor if they have any questions or concerns regarding the appropriate use of common/basic AI in this course.

> Students are expected to use AI responsibly and critically evaluate the outputs of AI tools, ensuring transparency, accountability, and ethical considerations in their utilization.

> Students can use basic AI tools for specific tasks approved by the instructor, such as grammar checking or citation formatting.
> Guidelines for AI usage will be provided to ensure alignment with course objectives and academic standards.

### Equity and Title IX

> Title IX of Education Amendments of 1972 (“Title IX”) prohibits discrimination based on sex, including sexual harassment, in education programs that receive federal funding. This includes providing support to anyone impacted by sex discrimination or sexual harassment.  The Title IX Coordinator is responsible for implementing Title IX and is in CWRU’s Office of Equity. The Title IX Coordinator is also responsible for making sure that the procedures in CWRU's policy prohibiting sex discrimination and sexual harassment are followed and all persons are treated fairly and with respect.
Members of the CWRU community and others should direct questions about the application of Title IX to situations impacting the CWRU community, and its educational programs and activities, to the Title IX Coordinator.  Information on the Office of Equity and Title IX is located [on the Office of Equity webpage](https://case.edu/equity/).
 
### CWRU Public Safety

> The Case Western Reserve University Division of Public Safety provides quality service, safety, and a positive educational experience for the campus community. Members of the CWRU community – students, faculty, staff, and guests – are encouraged to report all criminal actions, emergencies, or other public safety related incidents to CWRU Division of Public Safety. For an emergency, call 216-368-3333. For a non-emergency, call 216-368-3300. Members of the community are encouraged to [download the Spartan Safe app](https://case.edu/publicsafety/services/spartan-safe-app) which offers easy access to critical resources and safety tools.

## Laptop and cell phone use

Here is the official University policy:

> "Although having a laptop in class opens up new learning possibilities for students, it can be used in ways that are inappropriate. It is easy for your laptop to become a distraction to you and to those around you. Laptops are to be used only when essential to the task at hand. Please turn off or silence all cell/smart phones, tablets, and other electronic devices for the duration of the course. Inappropriate uses will be noted and may affect the final grade."

Professor Love adds that, in this class, the use of a laptop or other device is welcomed, and even encouraged, for taking notes on our slides, or following along with the presentation, or trying out ideas in R, but it is inappropriate for you to use such a machine for activities unrelated to the class during our time together. Silence your phone during class. The temptation to look at your phone or Facebook or email during class is nearly irresistible. Resist anyway, if only to avoid distracting your instructor and your fellow students. 

Thank you.

## Academic Integrity

Here is the official policy of the University on Academic Integrity.

> Any violation of the University’s Code of Ethics will not be tolerated. All forms of academic dishonesty including cheating, plagiarism, misrepresentation, and obstruction are violations of academic integrity standards and will result in a minimum penalty of receiving a zero for the assignment, the potential for failing the entire course. Cheating includes copying from another's work, falsifying problem solutions or laboratory reports, or using unauthorized sources, notes or computer programs. Plagiarism includes the presentation, without proper attribution, of another's words or ideas from printed or electronic sources. It is also plagiarism to submit, without the instructor's consent, an assignment in one class previously submitted in another. Misrepresentation includes forgery of official academic documents, the presentation of altered or falsified documents or testimony to a university office or official, taking an exam for another student, or lying about personal circumstances to postpone tests or assignments. Obstruction occurs when a student engages in unreasonable conduct that interferes with another's ability to conduct scholarly activity. Destroying a student's computer file, stealing a student's notebook, and stealing a book on reserve in the library are examples of obstruction. In addition, the incident will be reported to the Dean of Undergraduate Studies and Academic Review Board for undergraduates or Senior Associate Dean of Graduate Studies, for Graduate Students. 

The CWRU Statement of Ethics for graduate students can be found here: 
http://case.edu/gradstudies/about-the-school/policies-procedures/.

The University's [Academic Integrity Policy](https://case.edu/studentlife/ugadvisingsupport/academic-policies/academic-integrity) is also worth reading.


